import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProviders } from "./sessionProvider";
import Navbar from "./components/NavBar";
import ToasterProvider from "./ToastProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Research Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className="bg-gray-50 dark:bg-slate-900">
        <SessionProviders>
            <Navbar />
            <ToasterProvider />
            <div className="my-10">
              {children}
            </div>
        </SessionProviders>
      </body>
    </html>
  );
}
